# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CastRemoteNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CastRemoteNative
  workspace = ‘CastRemoteNativeWorkspace’

  pod 'google-cast-sdk'


  target 'CastRemoteNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CastRemoteNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CastRemoteNative-tvOS

  target 'CastRemoteNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
