# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CastRemoteNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CastRemoteNative
  workspace = ‘CastRemoteNative’

  pod 'google-cast-sdk'

  #for react
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
  ]

  target 'CastRemoteNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CastRemoteNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CastRemoteNative-tvOS

  target 'CastRemoteNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end