# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CastRemoteNative' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CastRemoteNative


  workspace = ‘CastRemoteNative’

  pod 'google-cast-sdk'

  #for react
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'


  target 'CastRemoteNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
